import Head from "next/head";
import {
  Navbar,
  Banner,
  Companies,
  Tabs,
  OpeningHours,
  Mentor,
  Students,
  Newsletter,
  Footer,
} from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Red Fly Academy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="title" content="Red Fly Academy next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/assets/logo/logo.svg" />
      </Head>
      <main>
        <Navbar />
        <Banner />
        {/* <Companies /> */}
        <Tabs />
        <Mentor />
        {/* <Students /> */}
        <OpeningHours />

        <div className="mt-20">
          <Newsletter />
        </div>
        <Footer />
      </main>
    </>
  );
}
